version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "${BROKER_PORT}:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    environment:
      - BROKER_USER=${BROKER_USER}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
      - BROKER_PORT=${BROKER_PORT}
    entrypoint: [ "sh", "-c", "
      if [ ! -f /mosquitto/config/passwd ]; then \
        touch /mosquitto/config/passwd && \
        mosquitto_passwd -b /mosquitto/config/passwd \"$BROKER_USER\" \"$BROKER_PASSWORD\"; \
      fi && \
      mosquitto -c /mosquitto/config/mosquitto.conf"
    ]
    networks:
      custom_net:


  objectdetection:
    image: ghcr.io/smartworkmcd/objectdetection:latest
    container_name: objectdetection
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    devices:
      - /dev/video0:/dev/video0
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USER=${BROKER_USER}
      - MQTT_PASSWORD=${BROKER_PASSWORD}
    networks:
      custom_net:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.69.0/24

